interface Action {
  title: string;
  description: string;
  impact: number;
  status: 'todo' | 'in-progress' | 'completed' | 'delayed';
  progress: number;
  deadline: string;
  scope: string;
  cost: number;
  estimatedReduction: number;
  priority: 'low' | 'medium' | 'high';
  implementationTime: string;
  category: string;
  responsible?: string;
  isAutoGenerated: boolean;
}

export const generateSuggestedActions = (emissionsData: any): Omit<Action, 'id'>[] => {
  const suggestions: Omit<Action, 'id'>[] = [];
  
  if (!emissionsData) return suggestions;

  const { scope1, scope2, scope3, calculation_data } = emissionsData;
  
  // Calculate deadlines (6 months to 2 years from now)
  const getDeadline = (months: number) => {
    const date = new Date();
    date.setMonth(date.getMonth() + months);
    return date.toISOString().split('T')[0];
  };

  // Scope 1 suggestions (Direct emissions)
  if (scope1 > 10) {
    suggestions.push({
      title: "Optimisation de la combustion",
      description: "Améliorer l'efficacité des équipements de combustion et réduire la consommation de combustibles fossiles",
      impact: scope1 * 0.15, // 15% reduction potential
      status: 'todo',
      progress: 0,
      deadline: getDeadline(12),
      scope: "Scope 1",
      cost: Math.min(scope1 * 500, 50000), // 500€ per tCO2e, max 50k€
      estimatedReduction: 15,
      priority: 'high',
      implementationTime: "6-12 mois",
      category: "Énergie",
      isAutoGenerated: true
    });

    if (scope1 > 50) {
      suggestions.push({
        title: "Transition vers des énergies renouvelables",
        description: "Remplacer les sources d'énergie fossiles par des alternatives renouvelables (solaire, éolien)",
        impact: scope1 * 0.6, // 60% reduction potential
        status: 'todo',
        progress: 0,
        deadline: getDeadline(18),
        scope: "Scope 1",
        cost: scope1 * 1200, // 1200€ per tCO2e
        estimatedReduction: 60,
        priority: 'high',
        implementationTime: "12-24 mois",
        category: "Énergie renouvelable",
        isAutoGenerated: true
      });
    }
  }

  // Scope 2 suggestions (Electricity)
  if (scope2 > 5) {
    suggestions.push({
      title: "Amélioration de l'efficacité énergétique",
      description: "Installation d'équipements plus efficaces et optimisation des systèmes électriques",
      impact: scope2 * 0.25, // 25% reduction potential
      status: 'todo',
      progress: 0,
      deadline: getDeadline(9),
      scope: "Scope 2",
      cost: Math.min(scope2 * 800, 75000), // 800€ per tCO2e, max 75k€
      estimatedReduction: 25,
      priority: 'medium',
      implementationTime: "3-9 mois",
      category: "Efficacité énergétique",
      isAutoGenerated: true
    });

    if (scope2 > 20) {
      suggestions.push({
        title: "Contrat d'électricité verte",
        description: "Souscrire à un contrat d'électricité 100% renouvelable avec garanties d'origine",
        impact: scope2 * 0.9, // 90% reduction potential
        status: 'todo',
        progress: 0,
        deadline: getDeadline(3),
        scope: "Scope 2",
        cost: scope2 * 50, // 50€ per tCO2e (surcoût électricité verte)
        estimatedReduction: 90,
        priority: 'high',
        implementationTime: "1-3 mois",
        category: "Énergie verte",
        isAutoGenerated: true
      });
    }
  }

  // Scope 3 suggestions (Indirect emissions)
  if (scope3 > 15) {
    suggestions.push({
      title: "Optimisation des déplacements professionnels",
      description: "Réduire les déplacements par la visioconférence et privilégier les transports bas carbone",
      impact: scope3 * 0.1, // 10% reduction potential
      status: 'todo',
      progress: 0,
      deadline: getDeadline(6),
      scope: "Scope 3",
      cost: scope3 * 200, // 200€ per tCO2e
      estimatedReduction: 10,
      priority: 'medium',
      implementationTime: "3-6 mois",
      category: "Transport",
      isAutoGenerated: true
    });

    if (scope3 > 50) {
      suggestions.push({
        title: "Optimisation de la chaîne d'approvisionnement",
        description: "Sélectionner des fournisseurs locaux et éco-responsables, réduire les emballages",
        impact: scope3 * 0.2, // 20% reduction potential
        status: 'todo',
        progress: 0,
        deadline: getDeadline(18),
        scope: "Scope 3",
        cost: scope3 * 400, // 400€ per tCO2e
        estimatedReduction: 20,
        priority: 'medium',
        implementationTime: "12-18 mois",
        category: "Achats",
        isAutoGenerated: true
      });

      suggestions.push({
        title: "Sensibilisation et formation des équipes",
        description: "Former les collaborateurs aux enjeux climatiques et bonnes pratiques environnementales",
        impact: scope3 * 0.05, // 5% reduction potential
        status: 'todo',
        progress: 0,
        deadline: getDeadline(6),
        scope: "Scope 3",
        cost: Math.min(scope3 * 100, 15000), // 100€ per tCO2e, max 15k€
        estimatedReduction: 5,
        priority: 'low',
        implementationTime: "2-6 mois",
        category: "Formation",
        isAutoGenerated: true
      });
    }
  }

  // High impact cross-scope actions
  const totalEmissions = scope1 + scope2 + scope3;
  if (totalEmissions > 100) {
    suggestions.push({
      title: "Stratégie globale de décarbonation",
      description: "Élaborer un plan de décarbonation complet avec objectifs SBTi et trajectoire Net Zero",
      impact: totalEmissions * 0.05, // 5% immediate impact, enables more
      status: 'todo',
      progress: 0,
      deadline: getDeadline(12),
      scope: "Transverse",
      cost: Math.min(totalEmissions * 150, 25000), // 150€ per tCO2e, max 25k€
      estimatedReduction: 5,
      priority: 'high',
      implementationTime: "6-12 mois",
      category: "Stratégie",
      isAutoGenerated: true
    });
  }

  return suggestions.sort((a, b) => b.impact - a.impact); // Sort by impact (highest first)
};